# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4286193fba399a39eafea26137b53d50d6196e71f8c12dca1e172c37d0132a734349a3b54cc25f6d0bdffc67ff65973a5e81c9eb27ad29618ea54795f6fc86de

test:
  secret_key_base: 18995767574bcde44f9423af6876837bda5bf56009d6c2c3a548014a85179b31e7f425ef0dc89ef1f88e6ed4618a8f677bc938318da196810a6e0b5c9e00fd2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
